name: Test Docker Build

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
permissions:
      contents: write
      statuses: write
jobs:
  clang-format:
    uses: umdlife/umd_workflows/.github/workflows/clang_format_lint.yaml@main
    secrets:
      PAT: ${{ secrets.UMDLIFEDEV_TOKEN }}

  rebuild_docker:
    strategy:
      matrix:
        parent_repo: [umd_darknet]
        stage: [dev_stage, prod_stage]
    uses: umdlife/umd_workflows/.github/workflows/rebuild_docker.yaml@main
    with:
      arch: linux/amd64
      stage: ${{ matrix.stage }}
      push: true
    secrets:
      PAT: ${{ secrets.UMDLIFEDEV_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
